name: docker-build-publish

on:
  workflow_call:
    inputs:
      soln-name:
        required: true
        type: string
      docker-name:
        required: true
        type: string

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_REPONAME: ${{ secrets.DOCKER_REPONAME }}

jobs:
  docker-build-publish:
    runs-on: self-hosted

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.soln-name }}-publish
          path: publish
      
      - name: Move Docker files to root
        run: |
          mv ./publish/Dockerfile ./publish/.dockerignore ./
    
      - name: List downloaded files
        run: ls -R

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ inputs.docker-name }} --progress=plain

      - name: List Docker images
        run: docker images ${{ inputs.docker-name }}

      - name: Tag image
        run: docker tag ${{ inputs.docker-name }} $DOCKER_USERNAME/$DOCKER_REPONAME:${{ inputs.docker-name }}
      
      - name: docker.io login
        run: echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin

      - name: docker push
        run: docker push $DOCKER_USERNAME/$DOCKER_REPONAME:${{ inputs.docker-name }}