name: docker-build-publish

on:
  workflow_call:
    inputs:
      soln-name:
        required: true
        type: string
      docker-name:
        required: true
        type: string

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_REPONAME: ${{ secrets.DOCKER_REPONAME }}

jobs:
  docker-build-publish:
    runs-on: self-hosted

    steps:
      - name: Clean working folder
        run: |
          ls -la ./
          rm -rf ./* || true
          rm -rf ./.??* || true
          ls -la ./

      - name: Remove old images
        run: |
          docker rm $(docker stop $(docker ps -a -q --filter ancestor=docker.io/${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPONAME }}:${{ inputs.docker-name }} --format="{{.ID}}"))
          && docker rm $(docker stop $(docker ps -a -q --filter ancestor=${{ inputs.docker-name }} --format="{{.ID}}")) || true

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.soln-name }}-publish
          path: publish
      
      - name: Move Docker files to root
        run: |
          mv ./publish/Dockerfile ./publish/.dockerignore ./
    
      - name: List downloaded files
        run: pwd && ls -R

      - name: Build the Docker image
        run: docker build --no-cache . --file Dockerfile --tag ${{ inputs.docker-name }} --progress=plain

      - name: List Docker images
        run: docker images ${{ inputs.docker-name }}

      - name: Tag image
        run: docker tag ${{ inputs.docker-name }} $DOCKER_USERNAME/$DOCKER_REPONAME:${{ inputs.docker-name }}
      
      - name: docker.io login
        run: echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin

      - name: docker push
        run: docker push $DOCKER_USERNAME/$DOCKER_REPONAME:${{ inputs.docker-name }}

      - name: Stop all containers
        run: docker container stop $(docker container ls -aq) || true

      - name: Remove dangling images
        run: docker images -f dangling=true || true

      - name: Remove all exited containers
        run: docker rm $(docker ps -a -f status=exited -q) || true

      - name: Clean up Docker images
        run: docker rmi $(docker images -f dangling=true -q) || true