name: dotnet-build-test

on:
  workflow_call:
    inputs:
      soln-name:
        required: true
        type: string

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_REPONAME: ${{ secrets.DOCKER_REPONAME }}

jobs:
  docker-build-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.soln-name }}-publish

      - name: Set image name env var
        run:  >-
          SOLN_NAME_LOWER=$(echo ${{ inputs.soln-name }} | tr "[:upper:]" "[:lower:]") 
          && echo SOLN_NAME_LOWER="$SOLN_NAME_LOWER"
          && echo "IMAGE_NAME=$(echo "$SOLN_NAME_LOWER" | tr . -)" >> $GITHUB_ENV

      - name: Test image name env var
        run: echo IMAGE_NAME="$IMAGE_NAME"

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME --progress=plain

      - name: List Docker images
        run: docker images $IMAGE_NAME

      - name: Tag image
        run: docker tag $IMAGE_NAME $DOCKER_USERNAME/$DOCKER_REPONAME:$IMAGE_NAME
      
      - name: docker.io login
        run: echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin

      - name: docker.io login
        run: docker push $DOCKER_USERNAME/$DOCKER_REPONAME:$IMAGE_NAME