name: 'dotnet-build-test'

on:
  workflow_call:
    inputs:
      soln-name:
        required: true
        type: string

jobs:
  nuget-push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.soln-name }}-nugets
    - name: Nuget push
      shell: bash
      env:
        AZURE_PAT: ${{ secrets.AZURE_PAT }}
        AZURE_USERNAME: ${{ secrets.AZURE_USERNAME }}
      run: dotnet nuget push --api-key AzureNuGetV3 bin/Release/*.nupkg 