name: 'dotnet-build-test'

on:
  workflow_call:
    inputs:
      soln-name:
        required: true
        type: string

env:
  BUILD_CONFIGURATION: ${{ secrets.BUILD_CONFIGURATION }}
  BUILD_VERSION: ${{ secrets.BUILD_VERSION_MAJOR }}.${{ secrets.BUILD_VERSION_MINOR }}.$GITHUB_RUN_NUMBER

jobs:
  build-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Dotnet restore
      shell: bash
      env:
        AZURE_USERNAME: ${{ secrets.AZURE_USERNAME }}
        AZURE_PAT: ${{ secrets.AZURE_PAT }}
        GH_USERNAME: ${{ secrets.GH_USERNAME }}
        GH_PAT: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo AZURE_PAT="$AZURE_PAT" && echo AZURE_USERNAME="$AZURE_USERNAME" && dotnet restore
    - name: Dotnet build
      shell: bash
      env:
        BUILD_VERSION: ${{ inputs.build-version }}
      run: |
        dotnet build "${{ inputs.soln-name }}.sln" --no-restore --configuration $BUILD_CONFIGURATION /p:Version=$BUILD_VERSION /p:AssemblyVersion=$BUILD_VERSION
    - name: Dotnet test
      shell: bash
      run: |
        dotnet test "${{ inputs.soln-name }}.sln" --configuration $BUILD_CONFIGURATION --test-adapter-path:. --filter "FullyQualifiedName!~IntegTests&FullyQualifiedName!~TestBase" --logger:"junit;LogFilePath=../../test-results/{assembly}-test-result.xml;MethodFormat=Class;FailureBodyFormat=Verbose" --diag test-results/test-logs.txt
    - name: Dotnet publish
      shell: bash
      run: |
        dotnet publish "${{ inputs.soln-name }}.sln" --configuration $BUILD_CONFIGURATION --no-restore --no-build --output ./publish
    - name: Artifact publish folder
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.soln-name }}-publish
        path: ./publish
    - name: Artifact nuget packages
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.soln-name }}-nugets
        path: '**/*.nupkg'