name: 'git-sync'

on:
  workflow_call:
    inputs:
      soln-name:
        required: true
        type: string
      scm-project-name:
        required: true
        type: string

jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set git config
      run: git config --global user.email ${{ secrets.GIT_EMAIL }} && git config --global user.name ${{ secrets.GIT_USERNAME }} && git config --global --list
    - name: Azure push
      run: git push --prune --verbose https://${{ secrets.AZURE_PAT }}@dev.azure.com/coultard/${{ inputs.scm-project-name }}/_git/${{ inputs.soln-name }} "+refs/remotes/origin/*:refs/heads/*" "+refs/tags/*:refs/tags/*"
    - name: GitLab push
      run: git push --prune --verbose https://oauth2:${{ secrets.GITLAB_PAT }}@gitlab.com/c7093/${{ inputs.scm-project-name }}/${{ inputs.soln-name }}.git "+refs/remotes/origin/*:refs/heads/*" "+refs/tags/*:refs/tags/*"'