name: k8s-deploy

on:
  workflow_call:
    inputs:
      soln-name:
        required: true
        type: string

jobs:
  docker-build-publish:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.soln-name }}-k8s
          path: ./k8s
    
      - name: List downloaded files
        run: ls -R
      
      # Deploy using kubectl
      - name: Create amespace if not exists
        run: kubectl create namespace ${{ secrets.K8S_NAMESPACE }} || true
      - name: Set context
        run: kubectl config set-context --current --namespace=${{ secrets.K8S_NAMESPACE }}
      - name: Apply manifests
        run: kubectl apply -f k8s